title: Rafael Santos Blog
author:
  name: Rafael Santos
  email: rafa.can.dev@gmail.com
description: A collection of tech articles I have been writting over the years for my own future reference.

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
