theme: minima
author:
  name: Rafael Santos
  email: "rafa.can.dev@gmail.com"
header_pages:
  - about.md
  - portfolio.md
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/rafacandev" }
